// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:echelon/models/auth_data.dart';
import 'package:echelon/models/class_entry.dart';
import 'package:echelon/models/daily_nutrition.dart';
import 'package:echelon/models/exercise.dart';
import 'package:echelon/models/exercise_set.dart';
import 'package:echelon/models/food_entry.dart';
import 'package:echelon/models/user.dart';
import 'package:echelon/models/workout.dart';
import 'package:echelon/models/workout_split.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AuthDataAdapter());
    registerAdapter(ClassEntryAdapter());
    registerAdapter(DailyNutritionAdapter());
    registerAdapter(ExerciseAdapter());
    registerAdapter(ExerciseSetAdapter());
    registerAdapter(FoodEntryAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(WorkoutAdapter());
    registerAdapter(WorkoutSplitAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AuthDataAdapter());
    registerAdapter(ClassEntryAdapter());
    registerAdapter(DailyNutritionAdapter());
    registerAdapter(ExerciseAdapter());
    registerAdapter(ExerciseSetAdapter());
    registerAdapter(FoodEntryAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(WorkoutAdapter());
    registerAdapter(WorkoutSplitAdapter());
  }
}
